### ISSUE TITLE
Regarding "evaluate_model" method

### ISSUE THREAD

**Issue by nrshoudi** [zefang-liu/yelp-review#1]
Hey Zefang Liu,

Thank you for your work.

<img width="662" alt="Screen Shot 2021-03-14 at 04 39 27" src="https://user-images.githubusercontent.com/17602996/111054667-5a8f8400-847f-11eb-856e-7a79c0c2601f.png">

I have a question regarding this method, when I run my code, it showed this error

<img width="608" alt="Screen Shot 2021-03-14 at 04 43 42" src="https://user-images.githubusercontent.com/17602996/111054731-e0133400-847f-11eb-822b-8f4d2400a871.png">

I hope my question is clear. I'll be appreciated if you could reply to me ASAP :')

Thank you,

**Comment by zefang-liu** [comment]
Hi Noura AlRashoudi, the repeated keyword should be removed. Thanks for noticing that.

**Comment by nrshoudi** [comment]
Thank you for your reply

I've tried this before "removing the repeated argument" and it shows that (evaluate_mode) method is not defined.

Then, I tried to add these two methods from the experiment section 

<img width="710" alt="Screen Shot 2021-03-14 at 05 55 26" src="https://user-images.githubusercontent.com/17602996/111055818-b6abd580-848a-11eb-97f2-1b817c55b802.png">


After that, this error appears 

<img width="762" alt="Screen Shot 2021-03-14 at 05 51 52" src="https://user-images.githubusercontent.com/17602996/111055819-bd3a4d00-848a-11eb-9b50-7f2be87ae2b3.png">


I think (evaluate_mode) method for CountVectorizer  is missing in the file

**Comment by nrshoudi** [comment]
It worked!

I forgot to import accuracy_score from sklearn :)

Thank you Zefang!
